FROM python:3.9
WORKDIR /arc-gltr-backend

COPY ./arc-gltr-backend/backend ./backend
COPY ./arc-gltr-backend/requirements.txt ./requirements.txt
COPY ./arc-gltr-backend/server.py ./server.py

RUN pip3 install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5001
CMD ["python3", "server.py"]
# CMD ["gunicorn", "-b", ":5010", "server"]