services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: arc-gltr-backend
    ports:
      - "5001:5001"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: arc-gltr-frontend
    ports:
      - "80:3000"